angular.module('taaModule').factory('RequirementDetailFactory', [function() {
	var model = {
		lstTestSuite: [{
			"req_category_id": 1,
			"testSuiteId": 810,
			"testPlanId": 845,
			"parentId": 0,
			"label": "原因分析1000",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"req_category_id": 2,
			"testSuiteId": 811,
			"testPlanId": 845,
			"parentId": 810,
			"label": "原因分析1000-1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"req_category_id": 3,
			"testSuiteId": 812,
			"testPlanId": 845,
			"parentId": 810,
			"label": "原因分析1000-2",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 813,
			"testPlanId": 845,
			"parentId": 0,
			"label": "データパターン1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 814,
			"testPlanId": 845,
			"parentId": 0,
			"label": "データパターン2",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 815,
			"testPlanId": 845,
			"parentId": 0,
			"label": "データパターン3",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 816,
			"testPlanId": 845,
			"parentId": 0,
			"label": "データパターン4",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 817,
			"testPlanId": 845,
			"parentId": 816,
			"label": "データパターン4-1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 818,
			"testPlanId": 845,
			"parentId": 817,
			"label": "データパターン4-1-1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 819,
			"testPlanId": 845,
			"parentId": 818,
			"label": "データパターン4-1-1-1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 820,
			"testPlanId": 845,
			"parentId": 819,
			"label": "データパターン4-1-1-1-1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}],
		classList: [{
			tagId: 1,
			tagName: '性能問題',
			requiment: 10,
			testSuite: 10,
			insident: 300
		}, {
			tagId: 2,
			tagName: '業務課XXXさん',
			requiment: 2,
			testSuite: 5,
			insident: 10
		}, {
			tagId: 3,
			tagName: 'セキュリティ',
			requiment: 9,
			testSuite: 9,
			insident: 90
		}, {
			tagId: 4,
			tagName: 'アイディア',
			requiment: 2,
			testSuite: 0,
			insident: 0
		}, {
			tagId: 5,
			tagName: 'タグ１',
			requiment: 0,
			testSuite: 0,
			insident: 0
		}, {
			tagId: 6,
			tagName: 'タグ２',
			requiment: 2,
			testSuite: 2,
			insident: 0
		}, {
			tagId: 7,
			tagName: 'タグ３',
			requiment: 3,
			testSuite: 3,
			insident: 0
		}, {
			tagId: 8,
			tagName: 'タグ４',
			requiment: 4,
			testSuite: 4,
			insident: 0
		}, {
			tagId: 9,
			tagName: 'タグ５',
			requiment: 5,
			testSuite: 5,
			insident: 0
		}, {
			tagId: 10,
			tagName: 'タグ６',
			requiment: 6,
			testSuite: 6,
			insident: 0
		}],
		tagList:[]
	};
	return model;
}]);