angular.module('taaModule').factory('UserFactory', [function() {
	var model = {
		userList: [{
			"userId": 45,
			"userName": "nguyen-tu",
			"firstName": "tu",
			"lastName": "nguyen thanh",
			"mailAddress": "aqthanhtu@gmail.com",
			"groupName": null,
			"validFlag": true,
			"versionNo": 1,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": false
		}, {
			"userId": 33,
			"userName": "duy-linh",
			"firstName": "nguyen",
			"lastName": "duylinh",
			"mailAddress": "duy-linh@system-exe.com.vn",
			"groupName": null,
			"validFlag": true,
			"versionNo": 13,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": true
		}, {
			"userId": 32,
			"userName": "thuylu10",
			"firstName": "thuylu10",
			"lastName": "thuylu10",
			"mailAddress": "thuylu10@system-exe.com.vn",
			"groupName": null,
			"validFlag": true,
			"versionNo": 2,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": true
		}, {
			"userId": 31,
			"userName": "testuser",
			"firstName": "EXE",
			"lastName": "太郎１",
			"mailAddress": "testuser@system-exe.co.jp",
			"groupName": null,
			"validFlag": true,
			"versionNo": 37,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": false
		}, {
			"userId": 30,
			"userName": "rtanaka",
			"firstName": "良一",
			"lastName": "田中",
			"mailAddress": "r-tanaka@system-exe.co.jp",
			"groupName": null,
			"validFlag": true,
			"versionNo": 4,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": true
		}, {
			"userId": 29,
			"userName": "うう　うう",
			"firstName": "うう",
			"lastName": "うう",
			"mailAddress": "akaste22188@yahoo.co.jp",
			"groupName": null,
			"validFlag": true,
			"versionNo": 9,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": true
		}, {
			"userId": 28,
			"userName": "うう　うう",
			"firstName": "うう",
			"lastName": "うう",
			"mailAddress": "akaste22187@yahoo.co.jp",
			"groupName": null,
			"validFlag": true,
			"versionNo": 4,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": true
		}, {
			"userId": 27,
			"userName": "mai-danh01",
			"firstName": "健太",
			"lastName": "鈴木",
			"mailAddress": "danhnguyen22187@gmail.com",
			"groupName": null,
			"validFlag": false,
			"versionNo": 3,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": false
		}, {
			"userId": 26,
			"userName": "test",
			"firstName": "test",
			"lastName": "test",
			"mailAddress": "thanh-son@system-exe.com.vn.jp",
			"groupName": null,
			"validFlag": true,
			"versionNo": 12,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": true
		}, {
			"userId": 25,
			"userName": "h-seki",
			"firstName": "秀健",
			"lastName": "関",
			"mailAddress": "h-seki@system-exe.co.jp",
			"groupName": null,
			"validFlag": true,
			"versionNo": 58,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": true
		}, {
			"userId": 26,
			"userName": "h-seki",
			"firstName": "秀健",
			"lastName": "関",
			"mailAddress": "h-seki@system-exe.co.jp",
			"groupName": null,
			"validFlag": true,
			"versionNo": 58,
			"registered": false,
			"roleId": null,
			"systemAdminFlag": true
		}],
		kubun: [{
			name: '無効',
			value: false
		}, {
			name: '有効',
			value: true
		}],
		listLang: [{
			id: 0,
			name: 'Japanese(日本語)',
		}, {
			id: 1,
			name: 'English(英語)',
		}],
	};
	return model;
}]);