angular.module('taaModule').factory('RequirementFactory', [function() {
	var model = {
		showOption:true,
		width:250,
		lstTestSuite: [{
			"req_category_id": 1,
			"testSuiteId": 810,
			"testPlanId": 845,
			"parentId": 0,
			"label": "原因分析1000",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"req_category_id": 2,
			"testSuiteId": 811,
			"testPlanId": 845,
			"parentId": 810,
			"label": "原因分析1000-1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"req_category_id": 3,
			"testSuiteId": 812,
			"testPlanId": 845,
			"parentId": 810,
			"label": "原因分析1000-2",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 813,
			"testPlanId": 845,
			"parentId": 0,
			"label": "データパターン1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 814,
			"testPlanId": 845,
			"parentId": 0,
			"label": "データパターン2",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 815,
			"testPlanId": 845,
			"parentId": 0,
			"label": "データパターン3",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 816,
			"testPlanId": 845,
			"parentId": 0,
			"label": "データパターン4",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 817,
			"testPlanId": 845,
			"parentId": 816,
			"label": "データパターン4-1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 818,
			"testPlanId": 845,
			"parentId": 817,
			"label": "データパターン4-1-1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 819,
			"testPlanId": 845,
			"parentId": 818,
			"label": "データパターン4-1-1-1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}, {
			"testSuiteId": 820,
			"testPlanId": 845,
			"parentId": 819,
			"label": "データパターン4-1-1-1-1",
			"children": "",
			"planScaleValue": null,
			"actualScaleValue": null
		}],
		listTag: [{
			tagId: 1,
			tagName: '性能問題',
			total: 320
		}, {
			tagId: 2,
			tagName: '業務課XXXさん',
			total: 17
		}, {
			tagId: 3,
			tagName: 'セキュリティ',
			total: 108
		}, {
			tagId: 4,
			tagName: 'アイディア',
			total: 2
		}, {
			tagId: 5,
			tagName: 'タグ１',
			total: 0
		}, {
			tagId: 6,
			tagName: 'タグ２',
			total: 4
		}, {
			tagId: 7,
			tagName: 'タグ３',
			total: 6
		}, {
			tagId: 8,
			tagName: 'タグ４',
			total: 8
		}, {
			tagId: 9,
			tagName: 'タグ５',
			total: 10
		}, {
			tagId: 10,
			tagName: 'タグ６',
			total: 12
		}],
	};
	return model;
}]);